---
- hosts: localhost
  connection: local
  become: true

  tasks: 
  -  name: install packages
     package:
      name: 
        - htop
        - tmux
        - vim-nox
        - python3-psutil

  - name: copy wallpaper file
    copy: 
      src: files/0011.jpg
      dest: /usr/share/backgrounds/pop/ansible-wallpaper2.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: popos-test
    dconf: 
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper2.png'"

  - name: set wallpaper position
    become_user: popos-test
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"



