---
- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

- name: update_tmux_plugin_perms
  file:
    path: /home/popos-test/.tmux/plugins
    owner: popos-test
    group: popos-test
    recurse: true

- name: update_vim_bundle_perms
  file:
    path: /home/popos-test/.vim/bundle
    owner: popos-test
    group: popos-test
    recurse: true
